# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tlasso1 <- function(x, y, q, s, grid_tau) {
    .Call(`_CSurf_tlasso1`, x, y, q, s, grid_tau)
}

ConstructBasis <- function(x, m = 3L) {
    .Call(`_CSurf_ConstructBasis`, x, m)
}

ncvxGroupReg <- function(X, Y, group, G, lambda = -1, penalty = "gSCAD", phi0 = 0.001, gamma = 1.5, epsilon_c = 0.001, epsilon_t = 0.001, iteMax = 500L, intercept = FALSE, itcpIncluded = FALSE) {
    .Call(`_CSurf_ncvxGroupReg`, X, Y, group, G, lambda, penalty, phi0, gamma, epsilon_c, epsilon_t, iteMax, intercept, itcpIncluded)
}

